######################################################################################################################################################
# docker-compose.yml: Saleor Application Compose Stack
# Purpose: Docker compose stack for the saleor applicationfor use in Code:You's DevOps w/ AWS Final Project which utilizes Saleor to demonstrate
#   students understanding of Docker, CI/CD pipelines, Github Workflows, and AWS deployment.
# Written By: James D. Glosser (demonicurges05@gmail.com)
######################################################################################################################################################
services:
  api:
    image: saleor-api
    build:
      context: ./saleor-api
      dockerfile: Dockerfile
    env_file:
      - common.env
      - backend.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - saleor-media:/app/media 
    networks:
      - saleor-backend-tier
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:8000/health/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s

  dashboard:
    image: saleor-dashboard
    build:
      context: ./saleor-dashboard
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - saleor-backend-tier
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:80 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
    ports:
      - "5432:5432"
    volumes:
      - saleor-db:/var/lib/postgresql/data\
      - ./replica_user.sql:/docker-entrypoint-initdb.d/replica_user.sql
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saleor -d saleor"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - saleor-redis:/data
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  saleor-backend-tier:

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
  saleor-media:
    driver: local